# Generated by Django 5.2.8 on 2025-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/pdf_thumbnails/'),
        ),
    ]
