# Generated by Django 5.2.8 on 2025-11-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_pdf_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf_type',
            field=models.CharField(blank=True, choices=[('auto', 'Auto-Generated'), ('manual', 'Manual Upload')], default='manual', max_length=10, null=True),
        ),
    ]
