# Generated by Django 5.2.8 on 2025-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_pdf_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pdf_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('manual', 'Manual Blog'), ('pdf', 'PDF Blog')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
