# Generated by Django 5.2.8 on 2025-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20251108_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
